model_options:
  create_case_dir: /global/u1/y/yazbeck/E3SM_code/cime/scripts/
  run_dir: /global/cscratch1/sd/yazbeck/e3sm_scratch/cori-knl/
  working_dir: /global/cscratch1/sd/yazbeck/
parameters:
  vcmax_np1: 3.510012531136571
  vcmax_np2: 0.7956039108285113
  vcmax_np3: 0.07525398929302683
