optimization_options:
  objective_options:
    objectives:
      - name: rmse
        boa_metric: RootMeanSquaredError
    outcome_constraints: []
  scheduler:
    total_trials: 60
  experiment:
    name: 'US_LA3_Wetl_C3Gra_Trans'
    start_year: 2012
    start_month: 1
    end_year: 2012
    end_month: 11
    model_var: ['CH4_SURF_AERE_SAT','CH4_SURF_AERE_UNSAT','FINUNDATED']
    obs_var: 'FCH4'
    obs2mod_unit_conv: 0.000000001
  output_dir: '/global/cscratch1/sd/yazbeck/US_LA3_Wetl_C3Gra_Trans/ParamOutput/'
  input_dir: '/global/cscratch1/sd/yazbeck/US_LA3_Wetl_C3Gra_Trans/ParamInput/'
  obsfile: '/global/cscratch1/sd/yazbeck/US_LA3_Wetl_C3Gra_Trans/ParamInput/ProcECData.csv'
  config_file:
    name: 'US_LA3_Wetl_C3Gra_Trans_optimization_config.yml'
  generation_strategy:
    steps:
      - model: SOBOL
        num_trials: 5
        min_trials_observed: 5
      - model: GPEI
        num_trials: -1
        max_parallelism: 10

model_options:
  create_case_dir: '/global/u1/y/yazbeck/E3SM_code/cime/scripts/'
  working_dir: '/global/cscratch1/sd/yazbeck/'
  run_dir: '/global/cscratch1/sd/yazbeck/e3sm_scratch/cori-knl/'

parameters:
  f_ch4:
    type: range
    bounds: [0.0,0.5]
    value_type: float