model_options:
  create_case_dir: /global/u1/y/yazbeck/E3SM_code/cime/scripts/
  run_dir: /global/cscratch1/sd/yazbeck/e3sm_scratch/cori-knl/
  working_dir: /global/cscratch1/sd/yazbeck/
parameters:
  vcmax_np1: 2.0390744788366004
  vcmax_np2: 0.8674823806339051
  vcmax_np3: 0.04970665443359403
