model_options:
  create_case_dir: /global/u1/y/yazbeck/E3SM_code/cime/scripts/
  run_dir: /global/cscratch1/sd/yazbeck/e3sm_scratch/cori-knl/
  working_dir: /global/cscratch1/sd/yazbeck/
parameters:
  MeasAereResis: 7.317375940252094e-07
  f_ch4: 0.36176841892302036
