model_options:
  create_case_dir: /global/u1/y/yazbeck/E3SM_code/cime/scripts/
  run_dir: /global/cscratch1/sd/yazbeck/e3sm_scratch/cori-knl/
  working_dir: /global/cscratch1/sd/yazbeck/
parameters:
  vcmax_np1: 2.373645029962063
  vcmax_np2: 1.257183470763266
  vcmax_np3: 0.31122037628665566
