model_options:
  create_case_dir: /global/u1/y/yazbeck/E3SM_code/cime/scripts/
  run_dir: /global/cscratch1/sd/yazbeck/e3sm_scratch/cori-knl/
  working_dir: /global/cscratch1/sd/yazbeck/
parameters:
  vcmax_np1: 3.7323774882982725
  vcmax_np2: 0.7590341130121051
  vcmax_np3: 0.17030865190675584
