model_options:
  create_case_dir: /global/u1/y/yazbeck/E3SM_code/cime/scripts/
  run_dir: /global/cscratch1/sd/yazbeck/e3sm_scratch/cori-knl/
  working_dir: /global/cscratch1/sd/yazbeck/
parameters:
  vcmax_np1: 2.7218344807624817
  vcmax_np2: 0.14898515492677689
  vcmax_np3: 0.033447153866291046
